### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by PhilippvK** [alxhoff/STM32-uGFX-Cmake#4]
Shouldn't the downloaded Libraries are in the `.gitignore` file or been imported as submodules? And should the Lab-Computers also download the Libs individually (disk quote is likely 2GB or so...) or fetch them from the RCS NAS?

**Comment by alxhoff** [comment]
This project is more intended for those wanting to set it up on their personal machines. The RCS setup probably doesn't need much changing, except the actual demo code. People are just always having problems setting up the toolchain on their own machines.
