### ISSUE TITLE
Is uGFX_LLD_CONFIG really required?

### ISSUE THREAD

**Issue by PhilippvK** [alxhoff/STM32-uGFX-Cmake#8]
_Short Question:_

The following code snipped from `cmake/FinduGFX.cmake` does not make sense to me.
```
if(NOT uGFX_LLD_CONFIG)
    MESSAGE("No uGFX_LLD_CONFIG given, this may result in an error")
ELSE()
    LIST(APPEND uGFX_INCLUDE_DIRS ${uGFX_LLD_CONFIG})
ENDIF()
```

What value should this variable have and do you set in in your configuration?

**Comment by alxhoff** [comment]
I believe this is the variable you can use to pass the lld (low level drier) config file needed for the platform's screen device. example ones can be found in `drivers/gdisp/${DRIVER}/gdisp_lld_config.h` and they do things like specify screen rotation. This build has the config directly in the include folder so I don't need to pass it a separate directory to include.

**Comment by alxhoff** [comment]
just noticed your commit 99dd3507e4e21fa90994f61f5b836b5daeedb044. The `uGFX_LLD_CONFIG` variable could be used if you wanted to move the config into a config folder.

**Comment by PhilippvK** [comment]
Thanks for making this clear. Wouldn’t it be more straightforward if the Variable name contains `DIR`? I always thought I have to pass the file itself.

**Comment by alxhoff** [comment]
> Thanks for making this clear. Wouldn’t it be more straightforward if the Variable name contains `DIR`? I always thought I have to pass the file itself.

yes that would be a bit clearer. PR it [here](https://github.com/ObKo/stm32-cmake).

**Comment by PhilippvK** [comment]
> just noticed your commit [99dd350](https://github.com/alxhoff/STM32-uGFX-Cmake/commit/99dd3507e4e21fa90994f61f5b836b5daeedb044). The `uGFX_LLD_CONFIG` variable could be used if you wanted to move the config into a config folder.

This has nothing to do with UGFX. I moved the following files into the `config` directory:
- GDB Configuration
- Eclipse and VSCode Config File Templates

**Comment by alxhoff** [comment]
No I mean if your were to do a similar thing and move the lld config to the same directory then it would be a useful variable
